name: SemVer Release Workflow

run-name: "Releasing ${{ github.event.repository.name }} #${{github.run_number}}"

# Trigger workflow manually
on:
  workflow_dispatch:

env:
  BRANCH_NAME: ${{ github.ref_name }}
  TRUNK_BRANCH_NAME: ${{ github.event.repository.default_branch }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    if: github.repository_owner == 'ikmdev'
    steps:
      - name: Verify Branch
        if: env.BRANCH_NAME != env.TRUNK_BRANCH_NAME
        run: |
          echo "ERROR: Attempting to release from branch ${{ env.BRANCH_NAME }}. Release from ${{ env.TRUNK_BRANCH_NAME }} branch only."
          exit 1

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{secrets.IKMDEVOPS_PAT_TOKEN}}

      - name: Extrapolate IKM Release Property
        run: |
          CORE_VERSION=$(mvn help:evaluate -D'expression=core.artifact.version' -q -D'forceStdout')
          RC_VERSION=$(mvn help:evaluate -D'expression=core.artifact.release' -q -D'forceStdout')
          RC_NUMBER=$(echo "$RC_VERSION" | grep -o -E '[0-9]+')
          NEW_RC_NUMBER=$(1 + RC_NUMBER)
          echo "$CORE_VERSION-$RC_NUMBER"
          exit 1



      - name: Shared Release Action
        uses: ikmdev/maven-semver-release-action@v2
        with:
          version_type: 'pre-release'
          github_token: ${{secrets.GITHUB_TOKEN}}
